/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/esqueleto2.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/esqueleto2.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.052}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Bones___Vray} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Bones___Vray} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Brown___Vray} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.White___Vray} />
      </group>
    </group>
  )
}

useGLTF.preload('/esqueleto2.glb')
